# Generated by Django 3.1.12 on 2023-03-24 14:30

from django.db import migrations, models
import djongo.models.fields
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('gender', models.CharField(default='', max_length=100)),
                ('product_id', models.CharField(max_length=100)),
                ('product_title', models.CharField(default='', max_length=100)),
                ('product_description', models.TextField(default='', max_length=100)),
                ('brand', models.CharField(default='', max_length=50)),
                ('source', models.CharField(default='', max_length=50)),
                ('product_categories', djongo.models.fields.JSONField()),
                ('url', models.URLField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('discount', models.DecimalField(decimal_places=7, max_digits=19)),
                ('currency_code', models.CharField(default='', max_length=100)),
                ('stock', models.IntegerField(default=1)),
                ('stock_level', models.IntegerField(default=1)),
                ('additional_ids', djongo.models.fields.JSONField(blank=True, null=True)),
                ('image_urls', djongo.models.fields.JSONField(blank=True, null=True)),
                ('position', djongo.models.fields.JSONField(blank=True, null=True)),
                ('product_imgs_src', djongo.models.fields.JSONField(blank=True, null=True)),
                ('images', djongo.models.fields.ArrayField(blank=True, model_container=products.models.Image, null=True)),
            ],
        ),
    ]
