# Generated by Django 3.1.12 on 2023-03-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_title',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
    ]
